version: '3.8'  # Define the Compose file format version

services:
  backend:
    build:
      context: ./backend  # Path to your backend folder
      dockerfile: dockerfile  # Dockerfile for the backend
    container_name: backend_api
    ports:
      - "5000:5000"  # Expose Flask API on port 5000
    networks:
      - app-network  # Connect backend to the same network
    environment:
      - FLASK_ENV=production  # You can define environment variables here
      - DATABASE_URL=your_database_url  # Replace with actual database connection string
    env_file: 
      - ./backend/.env  # Path to your .env file


  frontend:
    build:
      context: ./vue-project  # Path to your frontend folder
      dockerfile: dockerfile  # Dockerfile for the frontend
    container_name: frontend_vue
    ports:
      - "8080:80"  # Expose Vue.js app on port 8080
    networks:
      - app-network  # Connect frontend to the same network
    environment:
      - VITE_APP_API_URL==http://backend:5000  # URL for backend communication

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_auth
    environment:
      - KEYCLOAK_ADMIN=admin@shotsheet.com
      - KEYCLOAK_ADMIN_PASSWORD=Whit123+
    ports:
      - "8081:8080"  # Expose Keycloak on port 8081
    networks:
      - app-network  # Connect Keycloak to the same network
    command: ["start-dev"]  # Start Keycloak in development mode

networks:
  app-network:
    driver: bridge  # Use the default bridge driver
